(#117) 메일 전송
jobda-keychain/keychain pull request #132
Opened 2022-01-18 07:19 UTC by Silver-Deer

2022-01-18 15:16 UTC, shfksekdrms2 commented on src/main/java/com/jobda/keychain/KeychainApplication.java
>  @EnableFeignClients
feignClients 설정 config 파일이랑
enableAsync 설정 config 파일 분리해서 올리면좋을거같아요~!

2022-01-18 15:16 UTC, shfksekdrms2 commented on src/main/java/com/jobda/keychain/service/UserService.java
> +            URI uri = URI.create(environment.getServerDomain()+"/users/default");
도메인 정보는 상수로 관리되면 좋을거같아요

2022-01-18 15:16 UTC, shfksekdrms2 commented on src/test/resources/application.yml
> +            protocols: TLSv1.2
test 코드로 메일 발송 테스트하는게 없는거같은데 넣은이유가 있나요???

2022-01-19 01:21 UTC, syxxn commented on src/main/java/com/jobda/keychain/dto/response/JobdaAccountInfoResponse.java
> +    String email;
접근지정자는 일부러 명시 안한건가요?

2022-01-19 01:55 UTC, Silver-Deer commented on src/test/resources/application.yml
> +            protocols: TLSv1.2
test yml에 spring.mail 정보가 없으면 Test가 통과가 안돼서 추가했어요!

2022-01-19 02:00 UTC, Silver-Deer commented on src/main/java/com/jobda/keychain/dto/response/JobdaAccountInfoResponse.java
> +    String email;
추가했습니다!

2022-01-19 02:11 UTC, Silver-Deer commented on src/main/java/com/jobda/keychain/service/UserService.java
> +            URI uri = URI.create(environment.getServerDomain()+"/users/default");
도메인 정보는 환경마다 달라져서 상수로 관리하기 힘들지 않을까요?

2022-01-19 05:36 UTC, shfksekdrms2 commented on src/main/java/com/jobda/keychain/service/UserService.java
> +            URI uri = URI.create(environment.getServerDomain()+"/users/default");
아 path 말씀드린거였어요~!

2022-01-19 05:37 UTC, shfksekdrms2 commented on src/test/resources/application.yml
> +            protocols: TLSv1.2
음 그건 extension 을 동일하게 잡고해서 그런건데 test 코드 사용법이랑 연관이있어서 이거 시간있을때 잡고가면 좋을거같아요

2022-01-19 05:41 UTC, shfksekdrms2 approved these changes

2022-01-20 01:37 UTC, syxxn requested changes

2022-01-20 01:37 UTC, syxxn commented on src/main/java/com/jobda/keychain/service/UserService.java
> +            String email = authApiClient.getAccountInfo(uri, "Bearer " + token).getEmail();
Bearer같은 것도 상수로 관리하는 게 좋을 것 같아요!

2022-01-20 02:04 UTC, merged