[UPDATE] (#4) 유저 삭제 기능 수정
jobda-keychain/keychain pull request #49
Opened 2022-01-10 06:22 UTC by m04j00

2022-01-10 07:24 UTC, syxxn requested changes

2022-01-10 07:24 UTC, syxxn commented on src/main/java/com/jobda/keychain/controller/UserController.java
> +    public void deleteUser(@PathVariable Long id) {
객체로 받지 않고 long 기본 자료형 사용해도 될 것 같아요!

2022-01-10 07:24 UTC, syxxn commented on src/main/java/com/jobda/keychain/service/UserService.java
> +        if(accountRepository.findById(id).isPresent()) accountRepository.deleteById(id);
if문을 사용하지 않아도 deleteById랑 orElseThrow으로 줄일 수 있을 것 같아요

2022-01-10 07:24 UTC, syxxn commented on src/main/java/com/jobda/keychain/service/UserService.java
> +        else throw new UserIdNotFoundException();
매번 같은 객체를 만들 때 소모되는 시간을 줄이기 위해 EXCEPTION 상수를 만든거거든용
상수를 사용하는 쪽으로 예외처리 해주시면 좋을 것 같아요

2022-01-11 05:59 UTC, shfksekdrms2 commented on src/main/java/com/jobda/keychain/exception/UserIdNotFoundException.java
> +        super(404, "id not found");
비즈니스 로직에서 전반적으로 발생하는 이슈에 대한 exception 은 하나로 처리하면 좋을거같아요 

UserNotFoundException 과 유사한데 저렇게 없는 것들이 많을거같은데 각각 만들면 관리가 힘들거같긴해요 
데이터 조회시 없는 경우는 하나의 exception 으로 처리하면 좋을거같아요

2022-01-11 05:59 UTC, shfksekdrms2 commented on src/main/java/com/jobda/keychain/service/UserService.java
> +        if(accountRepository.findById(id).isPresent()) accountRepository.deleteById(id);
코드 스타일이긴한데 if/else 로 예외 처리하기 보단 
중간 예외, 중간 return 이런 처리들은 
accountRepository.findById(id).orElseThrow(() -> throw new UserIdNotFoundException());
이후에 비지니스 로직을 처리하는 편이에요

2022-01-11 05:59 UTC, shfksekdrms2 commented on gradlew
>  exec "$JAVACMD" "$@"
이거 idle 이 달라서 그런거같은데 계속 머지 될거같으면 ignore 파일에 넣어도 좋을거같기도 하고 아예 빼서 올리셔도 좋을거같아요

2022-01-13 08:18 UTC, shfksekdrms2 approved these changes

2022-01-14 02:27 UTC, merged